services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - common-network

  backend:
    build: ./dummy-backend
    ports:
      - "3000:3000"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge