name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Start Containers
        run: docker compose up -d

      - name: Check Containers
        run: docker compose ps

      - name: Stop Containers
        run: docker compose down